(function(){
  const steps=[
    ['Visão geral','O topo concentra as ações principais: busca individual, atalhos, críticos, atualização, tela cheia, relatório, tutorial e saída.','Use essa área como centro de comando. Ela foi pensada para operação rápida em tela grande.','#demoTopbar'],
    ['Filtro de máquina','Digite o código da máquina, como A1, B3 ou D10, para localizar rapidamente um card específico.','O filtro foi reduzido para ocupar menos espaço e manter os botões principais visíveis.','#demoSearch'],
    ['Filtros por forno','Selecione um ou mais fornos para visualizar somente os grupos necessários. O botão Todos os Fornos remove a filtragem.','Em operação, combine busca por máquina com filtro por forno para reduzir erros de lançamento.','#demoFurnaces'],
    ['Atalhos','O botão Atalhos abre um modal com links cadastráveis. Cada atalho tem nome, URL ou caminho de arquivo e comentário exibido ao passar o mouse.','Use para abrir documentos, planilhas, pastas, sistemas internos ou páginas de apoio sem sair do painel.','#demoShortcut',()=>showOnly('demoShortcutModal')],
    ['Tela cheia','O botão Tela cheia expande o painel para uso em TV, monitor de acompanhamento ou posto de abastecimento.','Para sair, use Esc ou o próprio botão quando o navegador permitir.','#demoFullscreen'],
    ['Cards de resumo','Os cards mostram totais gerais de moldes, blanks, neck rings, funis e máquinas críticas.','Eles ajudam a perceber rapidamente o estado geral antes de atuar em uma máquina específica.','#demoSummary'],
    ['Controle por máquina','Cada card contém os saldos e botões rápidos de entrada e saída. Registre somente na máquina correta.','A última atualização é recalculada quando houver alteração em molde, blank, neck ring ou funil.','#demoMachineCard'],
    ['Horário atual e última atualização','O card exibe o horário atual do sistema e o horário da última atualização da máquina.','Se a última atualização estiver antiga, valide se a máquina está parada, em manutenção ou sem movimentação recente.','#demoTimes'],
    ['Amostra e gráfico individual','Um clique no código da máquina marca ou remove amostra. Dois cliques rápidos abrem o modal com o gráfico individual.','Amostra é uma marcação visual. O gráfico individual é usado para auditoria por data e turno.','#demoMachineHead',()=>{document.getElementById('demoMachineCode').classList.add('active');document.getElementById('demoSampleBadge').classList.add('visible');showOnly('demoChartModal')}],
    ['Modo compacto','O modo compacto reduz elementos visuais para caber mais máquinas na tela.','Use quando o objetivo for acompanhamento geral, não lançamento detalhado.','#demoCompact',()=>document.getElementById('tutorialStage').classList.add('compact')],
    ['Ver críticos','O botão Ver Críticos filtra máquinas com estoque baixo ou condição crítica.','A regra operacional atual considera estoque baixo quando molde ou blank está próximo do limite configurado.','#demoCritical'],
    ['Gerar relatório','O relatório consolida os dados do painel para conferência, impressão ou envio.','Antes de gerar, confirme filtros, modo visual e dados atualizados.','#demoReport']
  ];
  const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
  let i=0; const title=qs('#tutorialStepTitle'), label=qs('#tutorialStepLabel'), desc=qs('#tutorialStepDescription'), call=qs('#tutorialCallout'), bar=qs('#tutorialProgressBar'), ring=qs('#spotlightRing'), lis=qsa('#tutorialStepsList li');
  function reset(){qsa('.pulse-target').forEach(e=>e.classList.remove('pulse-target'));qsa('.demo-modal').forEach(e=>e.classList.remove('visible'));qs('#tutorialStage').classList.remove('compact');qs('#demoMachineCode').classList.remove('active');qs('#demoSampleBadge').classList.remove('visible')}
  function showOnly(id){qsa('.demo-modal').forEach(e=>e.classList.remove('visible'));const el=document.getElementById(id);if(el)el.classList.add('visible')}
  function spotlight(sel){const el=qs(sel), stage=qs('#tutorialStage'); if(!el||!stage)return; const a=el.getBoundingClientRect(), b=stage.getBoundingClientRect(); ring.style.opacity='1'; ring.style.left=(a.left-b.left-8)+'px'; ring.style.top=(a.top-b.top-8)+'px'; ring.style.width=(a.width+16)+'px'; ring.style.height=(a.height+16)+'px'; el.classList.add('pulse-target')}
  function render(n){i=(n+steps.length)%steps.length; reset(); const s=steps[i]; label.textContent='Etapa '+(i+1); title.textContent=s[0]; desc.textContent=s[1]; call.textContent=s[2]; bar.style.width=((i+1)/steps.length*100)+'%'; lis.forEach((li,idx)=>li.classList.toggle('active',idx===i)); if(s[4])s[4](); requestAnimationFrame(()=>spotlight(s[3]));}
  qs('#prevStepBtn').addEventListener('click',()=>render(i-1)); qs('#nextStepBtn').addEventListener('click',()=>render(i+1)); qs('#startTutorialBtn').addEventListener('click',()=>{qs('#tutorialStageSection').scrollIntoView({behavior:'smooth',block:'start'});render(0)}); lis.forEach((li,idx)=>li.addEventListener('click',()=>render(idx))); window.addEventListener('resize',()=>render(i)); qsa('.demo-modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('visible')}));
  render(0);
})();
